### ISSUE TITLE
not working with current version of play-services-ads

### ISSUE THREAD

**Issue by fm-eb** [Wagawin/wagawin-sdk-android#1]
The SDK is only working with play-services-ads version 16.0.0
The current version ist 17.1.3
If using the current version the app crashes, because AdMob/AdPublisher is not set up correctly. See https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml

**Comment by WagawinChris** [comment]
Hey fm-eb,
thank you very much for pointing this out. We are actually only using a very small portion of the play services ads package (mainly the identifier). In the versions 17.0.+ they splitted the play service ads even further, so we can reduce the dependency to the package we really need. 
We will change the dependency to reflect this in our next update and change the documentation accordingly.

Best,
Chris

**Comment by WagawinChris** [comment]
Hey fm-eb,
we just released version 3.0.320. Please check the updated README file.
Hope everything is working now on your side.

Best,
Chris
